"""Shared scaffolding for basic 3-axis G-code dialects.

Every controller we post to right now (UCCNC, GRBL, and the LinuxCNC /
Mach3 variants that will slot in later) speaks the same subset of RS-274:
``G0/G1/G2/G3`` for motion, ``M3/M5`` for spindle, ``M6`` for tool
change, ``G4 P<s>`` for dwell, incremental I/J arc centres, parentheses
for comments. The differences between them are mostly:

- default preamble / footer / tool-change routine — handled by the
  per-machine macro system (see ``MachineDefinition.macros``), with
  ``default_macros`` on each post giving the controller-appropriate
  fallback when the project's macros are empty;
- display name (``name``), used by the UI when picking a post.

``BasicGcodePost`` absorbs everything else so each concrete
post-processor is usually just a subclass setting ``name`` and
``default_macros``. Override points (``_format_instruction``,
``_format_arc``, ``_fmt``, the coord/feed decimal constants) exist for
the rare cases where a controller really does speak a different
dialect — GRBL doesn't today, but LinuxCNC's canned cycles eventually
will.
"""
from __future__ import annotations

from collections.abc import Mapping

from pymillcam.engine.ir import IRInstruction, MoveType, Toolpath

COORD_DECIMALS = 4
FEED_DECIMALS = 1


class BasicGcodePost:
    """Parent for the UCCNC / GRBL / LinuxCNC / Mach3 family of posts.

    Subclasses set:

    * ``name`` — short display string, shown in the UI post picker.
    * ``default_macros`` — fallback snippets when the project's
      :class:`MachineDefinition` doesn't override them. Match what a
      vanilla controller of that dialect would accept with no setup.
    """

    name: str = "Basic"
    default_macros: Mapping[str, str] = {
        "program_start": "G21 G90",
        "program_end": "M5\nM30",
        "tool_change": "T{tool_number} M6",
    }

    def post_program(
        self,
        toolpaths: list[Toolpath],
        *,
        macros: Mapping[str, str] | None = None,
    ) -> str:
        # Each toolpath's IR already opens with a `(Profile: name)` /
        # `(Pocket: name)` / `(Drill: name)` comment courtesy of the
        # generator, so the post doesn't prepend its own — doing so
        # would produce two near-identical header comments per op.
        effective = dict(self.default_macros)
        if macros:
            effective.update(macros)
        lines: list[str] = ["(Generated by PyMillCAM)"]
        lines.extend(effective["program_start"].splitlines())
        current_feed: float | None = None

        for tp in toolpaths:
            for inst in tp.instructions:
                line, new_feed = _format_instruction(
                    inst,
                    current_feed,
                    tool_change_macro=effective["tool_change"],
                )
                if line is not None:
                    lines.append(line)
                current_feed = new_feed

        lines.extend(effective["program_end"].splitlines())
        return "\n".join(lines) + "\n"


def _format_instruction(
    inst: IRInstruction,
    current_feed: float | None,
    *,
    tool_change_macro: str = "T{tool_number} M6",
) -> tuple[str | None, float | None]:
    """Translate a single IR instruction to a G-code line.

    Returns (line, new_current_feed). `line` is None for instructions that
    produce no G-code output (e.g. unsupported types). When the instruction
    is a ``TOOL_CHANGE``, ``tool_change_macro`` is expanded with the target
    tool number — typically ``T<n> M6`` on ATC machines or a manual pause
    sequence on non-ATC setups.
    """
    t = inst.type

    if t is MoveType.COMMENT:
        return f"({inst.comment})", current_feed

    if t is MoveType.RAPID:
        parts = ["G0"]
        _append_xyz(parts, inst)
        return " ".join(parts) if len(parts) > 1 else None, current_feed

    if t is MoveType.FEED:
        parts = ["G1"]
        _append_xyz(parts, inst)
        new_feed = _append_feed(parts, inst.f, current_feed)
        return " ".join(parts) if len(parts) > 1 else None, new_feed

    if t is MoveType.ARC_CW:
        return _format_arc(inst, "G2", current_feed)

    if t is MoveType.ARC_CCW:
        return _format_arc(inst, "G3", current_feed)

    if t is MoveType.SPINDLE_ON:
        return (f"M3 S{inst.s}" if inst.s is not None else "M3"), current_feed

    if t is MoveType.SPINDLE_OFF:
        return "M5", current_feed

    if t is MoveType.TOOL_CHANGE:
        if inst.tool_number is None:
            return None, current_feed
        # `.replace` rather than `.format` — literal substitution won't
        # raise on unrelated braces that a user might paste into their
        # macro (e.g. comments with `{...}` or gcode-like sequences).
        # rstrip keeps a trailing newline in the macro from producing a
        # spurious blank line when joined with the rest of the program.
        expanded = tool_change_macro.replace(
            "{tool_number}", str(inst.tool_number)
        ).rstrip("\n")
        return expanded, current_feed

    if t is MoveType.DWELL:
        # inst.f doubles as dwell seconds until we add a dedicated field.
        if inst.f is None:
            return None, current_feed
        return f"G4 P{_fmt(inst.f, FEED_DECIMALS)}", current_feed

    if t is MoveType.COOLANT_ON:
        return "M8", current_feed

    if t is MoveType.COOLANT_OFF:
        return "M9", current_feed

    # MACRO is intentionally ignored for now; wired up when machine macros
    # are plumbed through post-processors.
    return None, current_feed


def _format_arc(
    inst: IRInstruction, code: str, current_feed: float | None
) -> tuple[str | None, float | None]:
    parts = [code]
    _append_xyz(parts, inst)
    if inst.i is not None:
        parts.append(f"I{_fmt(inst.i, COORD_DECIMALS)}")
    if inst.j is not None:
        parts.append(f"J{_fmt(inst.j, COORD_DECIMALS)}")
    new_feed = _append_feed(parts, inst.f, current_feed)
    if len(parts) == 1:
        return None, new_feed
    return " ".join(parts), new_feed


def _append_xyz(parts: list[str], inst: IRInstruction) -> None:
    if inst.x is not None:
        parts.append(f"X{_fmt(inst.x, COORD_DECIMALS)}")
    if inst.y is not None:
        parts.append(f"Y{_fmt(inst.y, COORD_DECIMALS)}")
    if inst.z is not None:
        parts.append(f"Z{_fmt(inst.z, COORD_DECIMALS)}")


def _append_feed(
    parts: list[str], feed: float | None, current_feed: float | None
) -> float | None:
    if feed is None:
        return current_feed
    if feed == current_feed:
        return current_feed
    parts.append(f"F{_fmt(feed, FEED_DECIMALS)}")
    return feed


def _fmt(value: float, decimals: int) -> str:
    """Format a float with fixed decimals, stripping trailing zeros/point."""
    text = f"{value:.{decimals}f}"
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"
