"""UCCNC post-processor.

Emits G-code for the UCCNC controller. Conventions used:

- G21 G90 G94 G17  — mm, absolute, feed per minute, XY plane
- G0                — rapid
- G1                — linear feed
- G2 / G3           — CW / CCW arc, center specified by incremental I/J
- M3 Snnnn          — spindle on (CW) at given RPM
- M5                — spindle off
- Tnn M6            — tool change
- ( ... )           — inline comment
- M30               — program end

Every motion line re-emits its G-word (no implicit modality) for clarity;
controllers accept the redundancy. Feed-rate modality is handled: F is
emitted only when it changes, since UCCNC's look-ahead treats a new F
as a real command.
"""
from __future__ import annotations

from pymillcam.engine.ir import IRInstruction, MoveType, Toolpath

COORD_DECIMALS = 4
FEED_DECIMALS = 1


class UccncPostProcessor:
    name = "UCCNC"

    def post_program(self, toolpaths: list[Toolpath]) -> str:
        # Each toolpath's IR already opens with a `(Profile: name)` /
        # `(Pocket: name)` / `(Drill: name)` comment courtesy of the
        # generator, so the post doesn't prepend its own — doing so would
        # produce two near-identical header comments per op.
        lines: list[str] = ["(Generated by PyMillCAM)", "G21 G90 G94 G17"]
        current_feed: float | None = None

        for tp in toolpaths:
            for inst in tp.instructions:
                line, new_feed = _format_instruction(inst, current_feed)
                if line is not None:
                    lines.append(line)
                current_feed = new_feed

        lines.extend(["M5", "M30"])
        return "\n".join(lines) + "\n"


def _format_instruction(
    inst: IRInstruction, current_feed: float | None
) -> tuple[str | None, float | None]:
    """Translate a single IR instruction to a G-code line.

    Returns (line, new_current_feed). `line` is None for instructions that
    produce no G-code output (e.g. unsupported types).
    """
    t = inst.type

    if t is MoveType.COMMENT:
        return f"({inst.comment})", current_feed

    if t is MoveType.RAPID:
        parts = ["G0"]
        _append_xyz(parts, inst)
        return " ".join(parts) if len(parts) > 1 else None, current_feed

    if t is MoveType.FEED:
        parts = ["G1"]
        _append_xyz(parts, inst)
        new_feed = _append_feed(parts, inst.f, current_feed)
        return " ".join(parts) if len(parts) > 1 else None, new_feed

    if t is MoveType.ARC_CW:
        return _format_arc(inst, "G2", current_feed)

    if t is MoveType.ARC_CCW:
        return _format_arc(inst, "G3", current_feed)

    if t is MoveType.SPINDLE_ON:
        return (f"M3 S{inst.s}" if inst.s is not None else "M3"), current_feed

    if t is MoveType.SPINDLE_OFF:
        return "M5", current_feed

    if t is MoveType.TOOL_CHANGE:
        if inst.tool_number is None:
            return None, current_feed
        return f"T{inst.tool_number} M6", current_feed

    if t is MoveType.DWELL:
        # inst.f doubles as dwell seconds until we add a dedicated field.
        if inst.f is None:
            return None, current_feed
        return f"G4 P{_fmt(inst.f, FEED_DECIMALS)}", current_feed

    if t is MoveType.COOLANT_ON:
        return "M8", current_feed

    if t is MoveType.COOLANT_OFF:
        return "M9", current_feed

    # MACRO is intentionally ignored for now; wired up when machine macros
    # are plumbed through post-processors.
    return None, current_feed


def _format_arc(
    inst: IRInstruction, code: str, current_feed: float | None
) -> tuple[str | None, float | None]:
    parts = [code]
    _append_xyz(parts, inst)
    if inst.i is not None:
        parts.append(f"I{_fmt(inst.i, COORD_DECIMALS)}")
    if inst.j is not None:
        parts.append(f"J{_fmt(inst.j, COORD_DECIMALS)}")
    new_feed = _append_feed(parts, inst.f, current_feed)
    if len(parts) == 1:
        return None, new_feed
    return " ".join(parts), new_feed


def _append_xyz(parts: list[str], inst: IRInstruction) -> None:
    if inst.x is not None:
        parts.append(f"X{_fmt(inst.x, COORD_DECIMALS)}")
    if inst.y is not None:
        parts.append(f"Y{_fmt(inst.y, COORD_DECIMALS)}")
    if inst.z is not None:
        parts.append(f"Z{_fmt(inst.z, COORD_DECIMALS)}")


def _append_feed(
    parts: list[str], feed: float | None, current_feed: float | None
) -> float | None:
    if feed is None:
        return current_feed
    if feed == current_feed:
        return current_feed
    parts.append(f"F{_fmt(feed, FEED_DECIMALS)}")
    return feed


def _fmt(value: float, decimals: int) -> str:
    """Format a float with fixed decimals, stripping trailing zeros/point."""
    text = f"{value:.{decimals}f}"
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"
