"""Geometry layer model — 2D entities imported from DXF or generated by patterns.

Entities are segment-first: `segments` is the authoritative, arc-preserving
representation. The Shapely `geom` property is a lazily-built shadow used for
read-only queries (containment, intersection, display) and discretizes arcs
to chords at a small default tolerance.

Single-point entities (e.g. DXF POINT) set `point` instead of `segments`.
"""
from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from uuid import uuid4

from pydantic import BaseModel, Field, model_validator
from shapely.geometry import Point
from shapely.geometry.base import BaseGeometry

from pymillcam.core.segments import (
    DEFAULT_SHADOW_TOLERANCE_MM,
    ArcSegment,
    LineSegment,
    Segment,
    segments_to_shapely,
)


class EntitySource(StrEnum):
    DXF = "dxf"
    SVG = "svg"
    PATTERN = "pattern"
    MANUAL = "manual"


class GeometryEntity(BaseModel):
    """A 2D geometric entity as a chain of line/arc segments or a single point.

    Contour entities populate `segments` and set `closed` appropriately.
    Point entities populate `point` and leave `segments` empty.
    """

    id: str = Field(default_factory=lambda: uuid4().hex)
    segments: list[Segment] = Field(default_factory=list)
    closed: bool = False
    point: tuple[float, float] | None = None
    source: EntitySource = EntitySource.DXF
    dxf_entity_type: str | None = None

    @model_validator(mode="after")
    def _validate_shape(self) -> GeometryEntity:
        if self.point is not None and self.segments:
            raise ValueError(
                "GeometryEntity cannot hold both `point` and `segments`; pick one"
            )
        if self.point is None and not self.segments:
            raise ValueError("GeometryEntity must have either `point` or `segments`")
        return self

    @property
    def is_closed(self) -> bool:
        return self.closed

    @property
    def geom(self) -> BaseGeometry:
        """Shapely shadow (chord-approximated) for queries / display.

        Rebuilt on each access. If this becomes a hot path we can memoize on
        an immutable copy of `segments`, but for typical part sizes the cost
        is negligible compared to Shapely's own ops.
        """
        if self.point is not None:
            return Point(*self.point)
        return segments_to_shapely(
            self.segments,
            closed=self.closed,
            tolerance=DEFAULT_SHADOW_TOLERANCE_MM,
        )


class GeometryLayer(BaseModel):
    """A named collection of geometric entities, typically one DXF layer."""

    name: str
    color: str = "#ffffff"
    visible: bool = True
    entities: list[GeometryEntity] = Field(default_factory=list)
    source_dxf_path: str | None = None
    import_timestamp: datetime | None = None

    def find_entity(self, entity_id: str) -> GeometryEntity | None:
        return next((e for e in self.entities if e.id == entity_id), None)


def describe_entity(entity: GeometryEntity) -> str:
    """Short human-readable description of an entity's dimensions.

    Covers the common shapes users want to verify at a glance:

    * POINT → ``Point (x, y)``
    * Full-circle arc → ``Circle Ø d mm``
    * Partial arc → ``Arc r=… mm, sweep=… °``
    * Single line → ``Line … mm``
    * Closed chain → ``Closed contour, … mm``
    * Open chain → ``Chain, N segs, … mm``

    Measurements in mm (project units); the caller is free to reformat.
    """
    if entity.point is not None:
        px, py = entity.point
        return f"Point ({px:.3f}, {py:.3f})"
    if not entity.segments:
        return "(empty entity)"
    if len(entity.segments) == 1:
        seg = entity.segments[0]
        if isinstance(seg, LineSegment):
            return f"Line {seg.length:.3f} mm"
        if isinstance(seg, ArcSegment):
            if seg.is_full_circle:
                return f"Circle Ø {2 * seg.radius:.3f} mm"
            return (
                f"Arc r={seg.radius:.3f} mm, "
                f"sweep={seg.sweep_deg:+.2f}°"
            )
    total_length = sum(s.length for s in entity.segments)
    if entity.closed:
        return (
            f"Closed contour, {len(entity.segments)} seg, "
            f"{total_length:.3f} mm"
        )
    return (
        f"Chain, {len(entity.segments)} seg, "
        f"{total_length:.3f} mm"
    )
