"""Geometry layer model — 2D entities imported from DXF or generated by patterns."""
from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator
from shapely import wkt
from shapely.geometry import LineString, Polygon
from shapely.geometry.base import BaseGeometry


class EntitySource(StrEnum):
    DXF = "dxf"
    SVG = "svg"
    PATTERN = "pattern"
    MANUAL = "manual"


class GeometryEntity(BaseModel):
    """A single 2D geometric entity backed by a Shapely object.

    `geom` holds a live Shapely object in memory and round-trips through WKT
    for JSON serialization so projects stay human-readable on disk.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    id: str = Field(default_factory=lambda: uuid4().hex)
    geom: BaseGeometry
    source: EntitySource = EntitySource.DXF
    dxf_entity_type: str | None = None

    @field_validator("geom", mode="before")
    @classmethod
    def _parse_geom(cls, v: Any) -> BaseGeometry:
        if isinstance(v, BaseGeometry):
            return v
        if isinstance(v, str):
            return wkt.loads(v)
        raise TypeError(f"geom must be a Shapely geometry or WKT string, got {type(v).__name__}")

    @field_serializer("geom")
    def _serialize_geom(self, g: BaseGeometry) -> str:
        return g.wkt

    @property
    def is_closed(self) -> bool:
        if isinstance(self.geom, Polygon):
            return True
        if isinstance(self.geom, LineString):
            return bool(self.geom.is_closed)
        return False


class GeometryLayer(BaseModel):
    """A named collection of geometric entities, typically one DXF layer."""

    name: str
    color: str = "#ffffff"
    visible: bool = True
    entities: list[GeometryEntity] = Field(default_factory=list)
    source_dxf_path: str | None = None
    import_timestamp: datetime | None = None

    def find_entity(self, entity_id: str) -> GeometryEntity | None:
        return next((e for e in self.entities if e.id == entity_id), None)
