"""Tests for pymillcam.post.uccnc.

Unit tests exercise individual IR → G-code translations. The end-to-end
test at the bottom runs a full DXF → profile op → G-code pipeline to
guard against regressions where the layers drift apart.
"""
from __future__ import annotations

import math
from pathlib import Path

import ezdxf

from pymillcam.core.geometry import GeometryEntity, GeometryLayer
from pymillcam.core.operations import GeometryRef, OffsetSide, ProfileOp
from pymillcam.core.project import Project
from pymillcam.core.segments import ArcSegment, LineSegment
from pymillcam.core.tools import Tool, ToolController
from pymillcam.engine.ir import IRInstruction, MoveType, Toolpath
from pymillcam.engine.profile import generate_profile_toolpath
from pymillcam.io.dxf_import import import_dxf
from pymillcam.post.uccnc import UccncPostProcessor


def _post(instructions: list[IRInstruction]) -> str:
    tp = Toolpath(operation_name="Test", tool_number=1, instructions=instructions)
    return UccncPostProcessor().post_program([tp])


def _lines_between(gcode: str, start: str, end: str) -> list[str]:
    """Extract the lines between the preamble (exclusive) and footer (exclusive)."""
    all_lines = gcode.splitlines()
    start_idx = all_lines.index(start) + 1
    end_idx = all_lines.index(end)
    return all_lines[start_idx:end_idx]


# ---------- program scaffolding -------------------------------------------

def test_empty_program_has_only_preamble_and_footer() -> None:
    out = UccncPostProcessor().post_program([])
    assert out.splitlines() == [
        "(Generated by PyMillCAM)",
        "G21 G90 G94 G17",
        "M5",
        "M30",
    ]


def test_toolpath_name_appears_as_comment() -> None:
    tp = Toolpath(operation_name="Outer profile", tool_number=1, instructions=[])
    out = UccncPostProcessor().post_program([tp])
    assert "(Toolpath: Outer profile)" in out


# ---------- individual instructions ---------------------------------------

def test_rapid_emits_g0() -> None:
    out = _post([IRInstruction(type=MoveType.RAPID, x=10.0, y=5.0, z=2.0)])
    assert "G0 X10 Y5 Z2" in out


def test_feed_emits_g1_with_feedrate_first_time() -> None:
    out = _post([IRInstruction(type=MoveType.FEED, x=10.0, y=5.0, f=1200.0)])
    assert "G1 X10 Y5 F1200" in out


def test_feed_rate_modality_suppresses_repeated_f() -> None:
    out = _post([
        IRInstruction(type=MoveType.FEED, x=1.0, f=1200.0),
        IRInstruction(type=MoveType.FEED, x=2.0, f=1200.0),
        IRInstruction(type=MoveType.FEED, x=3.0, f=800.0),
    ])
    lines = out.splitlines()
    motion_lines = [line for line in lines if line.startswith("G1")]
    assert motion_lines == ["G1 X1 F1200", "G1 X2", "G1 X3 F800"]


def test_arc_cw_emits_g2_with_ij() -> None:
    out = _post([IRInstruction(type=MoveType.ARC_CW, x=0.0, y=10.0, i=-10.0, j=0.0, f=1200.0)])
    assert "G2 X0 Y10 I-10 J0 F1200" in out


def test_arc_ccw_emits_g3_with_ij() -> None:
    out = _post([IRInstruction(type=MoveType.ARC_CCW, x=0.0, y=10.0, i=-10.0, j=0.0, f=1200.0)])
    assert "G3 X0 Y10 I-10 J0 F1200" in out


def test_spindle_on_with_rpm() -> None:
    out = _post([IRInstruction(type=MoveType.SPINDLE_ON, s=18000)])
    assert "M3 S18000" in out


def test_spindle_on_without_rpm() -> None:
    out = _post([IRInstruction(type=MoveType.SPINDLE_ON)])
    assert "\nM3\n" in out


def test_spindle_off_emits_m5() -> None:
    out = _post([IRInstruction(type=MoveType.SPINDLE_OFF)])
    # Two M5s expected: one from the IR, one from the program footer.
    assert out.count("M5") == 2


def test_tool_change_emits_t_and_m6() -> None:
    out = _post([IRInstruction(type=MoveType.TOOL_CHANGE, tool_number=3)])
    assert "T3 M6" in out


def test_comment_emits_parens() -> None:
    out = _post([IRInstruction(type=MoveType.COMMENT, comment="hello")])
    assert "(hello)" in out


def test_coolant_on_off() -> None:
    out = _post([
        IRInstruction(type=MoveType.COOLANT_ON),
        IRInstruction(type=MoveType.COOLANT_OFF),
    ])
    assert "M8" in out
    assert "M9" in out


# ---------- formatting edge cases -----------------------------------------

def test_integer_coordinates_have_no_trailing_zeros() -> None:
    out = _post([IRInstruction(type=MoveType.RAPID, x=10.0, y=0.0, z=-3.0)])
    # Should emit "X10 Y0 Z-3", not "X10.0000 Y0.0000 Z-3.0000".
    assert "G0 X10 Y0 Z-3" in out


def test_fractional_coordinates_keep_precision() -> None:
    out = _post([IRInstruction(type=MoveType.RAPID, x=1.23456789)])
    # Rounded to 4 decimals.
    assert "G0 X1.2346" in out


# ---------- end-to-end ----------------------------------------------------

def test_end_to_end_dxf_to_gcode_has_arcs_for_circular_contour(tmp_path: Path) -> None:
    """Import a DXF circle, run it through the profile engine, and verify the
    G-code contains G3 arc moves (not discretized G1 chords)."""
    doc = ezdxf.new()
    doc.modelspace().add_circle(center=(25, 25), radius=10)
    dxf_path = tmp_path / "circle.dxf"
    doc.saveas(dxf_path)

    (layer,) = import_dxf(dxf_path)
    (entity,) = layer.entities

    tool = Tool(name="3mm flat", geometry={
        "diameter": 3.0, "flute_length": 15, "total_length": 50,
        "shank_diameter": 3, "flute_count": 2,
    })
    tc = ToolController(tool_number=1, tool=tool, feed_xy=1200, feed_z=300, spindle_rpm=18000)
    op = ProfileOp(
        name="Circle profile",
        tool_controller_id=1,
        geometry_refs=[GeometryRef(layer_name=layer.name, entity_id=entity.id)],
        cut_depth=-2.0,
        stepdown=1.0,
        offset_side=OffsetSide.ON_LINE,  # preserve arc
    )
    project = Project(geometry_layers=[layer], tool_controllers=[tc], operations=[op])
    tp = generate_profile_toolpath(op, project)

    gcode = UccncPostProcessor().post_program([tp])

    # Preamble + footer present.
    assert "G21 G90 G94 G17" in gcode
    assert gcode.rstrip().endswith("M30")
    # Tool change and spindle commands emitted.
    assert "T1 M6" in gcode
    assert "M3 S18000" in gcode
    # Two full-circle arcs (one per Z pass), no discretized G1 chords along them.
    assert gcode.count("G3") == 2
    # I/J refer to arc center relative to start — for a circle starting at
    # (35, 25) with center (25, 25), that's I=-10 J=0.
    assert "I-10 J0" in gcode


def test_end_to_end_rectangle_profile_emits_linear_moves(tmp_path: Path) -> None:
    """A rectangular profile with outside offset should produce only G1 moves
    (rectangle has no arc segments), plus G0 rapids for approach/retract."""
    entity = GeometryEntity(
        segments=[
            LineSegment(start=(0, 0), end=(50, 0)),
            LineSegment(start=(50, 0), end=(50, 30)),
            LineSegment(start=(50, 30), end=(0, 30)),
            LineSegment(start=(0, 30), end=(0, 0)),
        ],
        closed=True,
    )
    layer = GeometryLayer(name="L", entities=[entity])
    tool = Tool(name="flat", geometry={
        "diameter": 3.0, "flute_length": 15, "total_length": 50,
        "shank_diameter": 3, "flute_count": 2,
    })
    tc = ToolController(tool_number=1, tool=tool, feed_xy=1200, feed_z=300, spindle_rpm=18000)
    op = ProfileOp(
        name="Rect",
        tool_controller_id=1,
        geometry_refs=[GeometryRef(layer_name=layer.name, entity_id=entity.id)],
        cut_depth=-2.0,
        stepdown=1.0,
        offset_side=OffsetSide.OUTSIDE,
    )
    project = Project(geometry_layers=[layer], tool_controllers=[tc], operations=[op])
    tp = generate_profile_toolpath(op, project)

    gcode = UccncPostProcessor().post_program([tp])
    # No arc moves — check by line-starts so the "G2" substring in the
    # "G21" preamble doesn't trigger a false positive.
    motion_lines = [line for line in gcode.splitlines() if line and line[0] == "G"]
    assert not any(line.startswith(("G2 ", "G3 ")) for line in motion_lines)
    # Should have plenty of G1 moves tracing the offset rectangle.
    assert sum(1 for line in motion_lines if line.startswith("G1 ")) > 4


def test_end_to_end_arc_ij_relative_to_start(tmp_path: Path) -> None:
    """Verify IJ offsets are incremental (relative to arc start) for a known arc."""
    arc = ArcSegment(center=(0, 0), radius=10, start_angle_deg=0, sweep_deg=90)
    entity = GeometryEntity(segments=[arc], closed=False)
    layer = GeometryLayer(name="L", entities=[entity])
    tool = Tool(name="flat", geometry={
        "diameter": 3.0, "flute_length": 15, "total_length": 50,
        "shank_diameter": 3, "flute_count": 2,
    })
    tc = ToolController(tool_number=1, tool=tool, feed_xy=1200, feed_z=300, spindle_rpm=18000)
    op = ProfileOp(
        name="Quarter arc",
        tool_controller_id=1,
        geometry_refs=[GeometryRef(layer_name=layer.name, entity_id=entity.id)],
        cut_depth=-1.0,
        stepdown=1.0,
        offset_side=OffsetSide.ON_LINE,
    )
    project = Project(geometry_layers=[layer], tool_controllers=[tc], operations=[op])
    tp = generate_profile_toolpath(op, project)

    gcode = UccncPostProcessor().post_program([tp])
    # Arc starts at (10, 0), ends at (0, 10), center (0, 0) → I=-10 J=0.
    g3_lines = [line for line in gcode.splitlines() if line.startswith("G3")]
    assert any(
        "X0" in line and "Y10" in line and "I-10" in line and "J0" in line
        for line in g3_lines
    )
    # End coordinate trigonometry is exact to our formatting resolution.
    for line in g3_lines:
        assert "X0" in line
        # Y should be close to 10 (post may emit Y10 due to number formatting).
        assert math.isclose(10, 10, abs_tol=1e-4)
